// 20 버티컬 정의. 각 계정 1개, 트렌드소스/포맷/톤/비주얼/후킹이 전부 다르다.
// (HARD CONSTRAINT #4: 계정 간 톤/템플릿/포맷 강제 분기)
//
// 소스 설정 규약:
//  - google_trends_rss: url = geo 포함 RSS 엔드포인트
//  - rss_news:          url = 개별 RSS/Atom 피드
//  - reddit_json:       params.subreddit, params.sort('hot'|'top'), params.t('day')
//  - hackernews:        params.tags 또는 params.query (Algolia)
//  - coingecko:         url 불필요 (trending 고정 엔드포인트)
//  - youtube_popular:   params.categoryId, params.regionCode (YOUTUBE_API_KEY 필요)
//  - naver_datalab:     params.keywordGroups (NAVER_CLIENT_ID/SECRET 필요)

import type { Vertical } from '../lib/types.js';

const GT = (geo = 'KR') => ({
  type: 'google_trends_rss' as const,
  label: `Google Trends ${geo}`,
  url: `https://trends.google.com/trending/rss?geo=${geo}`,
});

export const VERTICALS: Vertical[] = [
  {
    slug: 'money-brief',
    handle: { ig: '@money.brief.kr', fb: 'moneybriefkr' },
    topic: '경제/금리/환율',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '한겨레 경제', url: 'https://www.hani.co.kr/rss/economy/' },
      { type: 'rss_news', label: '연합 경제', url: 'https://www.yna.co.kr/rss/economy.xml' },
    ],
    format: 'card',
    cardTemplate: 'tpl-money-serif-dark',
    palette: ['#0B1F3A', '#1CA56A', '#F5F7FA'],
    typeface: 'GowunBatang',
    tone: '차분하고 신뢰감 있는 기자체. 단정적 표현 대신 근거 제시. 존댓말.',
    hookPattern: '숫자 충격 + "왜 지금" (예: "환율 1,450원 돌파 — 왜 지금 오르나")',
    ctaPattern: '"저장하고 오늘 환율 체크 → 프로필 링크"',
    postsPerDay: 15,
    bestHours: [7, 8, 12, 19, 21],
  },
  {
    slug: 'crypto-pulse',
    handle: { ig: '@crypto.pulse.kr', fb: 'cryptopulsekr' },
    topic: '코인/선물 시장',
    sources: [
      { type: 'coingecko', label: 'CoinGecko Trending' },
      { type: 'reddit_json', label: 'r/CryptoCurrency', params: { subreddit: 'CryptoCurrency', sort: 'hot' } },
    ],
    format: 'card',
    cardTemplate: 'tpl-crypto-neon-grid',
    palette: ['#08090D', '#F7931A', '#00E0B8'],
    typeface: 'Pretendard',
    tone: '빠르고 직설적. 트레이더 은어 허용하되 초보도 이해되게. 반말 금지, 간결한 존댓말.',
    hookPattern: '청산맵·펀딩비 시각화 + "지금 롱/숏 어디 몰렸나"',
    ctaPattern: '"펀딩비 매일 체크 → 팔로우"',
    postsPerDay: 15,
    bestHours: [8, 11, 14, 20, 23],
  },
  {
    slug: 'ai-daily',
    handle: { ig: '@ai.daily.kr', fb: 'aidailykr' },
    topic: 'AI 신규 툴/모델',
    sources: [
      { type: 'hackernews', label: 'HN front page', params: { tags: 'front_page' } },
      { type: 'reddit_json', label: 'r/artificial', params: { subreddit: 'artificial', sort: 'hot' } },
      { type: 'reddit_json', label: 'r/LocalLLaMA', params: { subreddit: 'LocalLLaMA', sort: 'hot' } },
    ],
    format: 'reel',
    cardTemplate: 'tpl-ai-mono-gradient',
    palette: ['#0D0D0F', '#7C5CFF', '#E9E4FF'],
    typeface: 'Pretendard',
    tone: '실용 얼리어답터. 과장 없이 "이거 무료임/이게 됨" 실물 데모 강조.',
    hookPattern: '"이거 무료임" 프레이밍 (예: "이 AI 영상편집 무료로 풀렸다")',
    ctaPattern: '"툴 링크 프로필에 → 저장 필수"',
    postsPerDay: 15,
    bestHours: [9, 13, 18, 21, 22],
  },
  {
    slug: 'dev-tip',
    handle: { ig: '@dev.tip.kr', fb: 'devtipkr' },
    topic: '개발 팁/에러 해결',
    sources: [
      { type: 'hackernews', label: 'HN Ask/Show', params: { tags: 'ask_hn' } },
      { type: 'reddit_json', label: 'r/programming', params: { subreddit: 'programming', sort: 'hot' } },
      { type: 'reddit_json', label: 'r/webdev', params: { subreddit: 'webdev', sort: 'top', t: 'day' } },
    ],
    format: 'card',
    cardTemplate: 'tpl-dev-terminal',
    palette: ['#0A0E14', '#39D353', '#C9D1D9'],
    typeface: 'JetBrainsMono',
    tone: '군더더기 없는 실무자체. 코드블록 중심. 결론부터.',
    hookPattern: '에러 메시지 그대로 썸네일 (예: "TypeError: undefined is not a function")',
    ctaPattern: '"막힌 에러 댓글로 → 다음 카드에서 해결"',
    postsPerDay: 15,
    bestHours: [10, 14, 16, 20, 22],
  },
  {
    slug: 'health-check',
    handle: { ig: '@health.check.kr', fb: 'healthcheckkr' },
    topic: '건강 정보',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '한겨레 사회', url: 'https://www.hani.co.kr/rss/society/' },
    ],
    format: 'reel',
    cardTemplate: 'tpl-health-clean-green',
    palette: ['#F3FBF6', '#1E8E5A', '#123B29'],
    typeface: 'Pretendard',
    tone: '따뜻하지만 정확. 단정 진단 금지, "재미/참고용" 고지 필수. 존댓말.',
    hookPattern: '흔한 오해 반박 (예: "물 8잔? 사실 이렇게 마시면 손해")',
    ctaPattern: '"내 몸 신호 저장 → 주 1회 건강 체크"',
    postsPerDay: 15,
    bestHours: [7, 12, 18, 21, 22],
  },
  {
    slug: 'food-trend',
    handle: { ig: '@food.trend.kr', fb: 'foodtrendkr' },
    topic: '음식/맛집 트렌드',
    sources: [
      GT('KR'),
      { type: 'naver_datalab', label: '네이버 데이터랩 음식', params: { keywordGroups: ['맛집', '신메뉴', '밀키트'] } },
    ],
    format: 'reel',
    cardTemplate: 'tpl-food-bold-closeup',
    palette: ['#1A1110', '#FF5A3C', '#FFE8DF'],
    typeface: 'Pretendard',
    tone: '군침 도는 감각적 카피. 짧고 리듬감. 가격 자막 강조.',
    hookPattern: '클로즈업 + 가격 자막 (예: "이 조합 3,900원")',
    ctaPattern: '"어디 건지 댓글 → 위치 공유"',
    postsPerDay: 15,
    bestHours: [11, 12, 17, 18, 21],
  },
  {
    slug: 'travel-cheap',
    handle: { ig: '@travel.cheap.kr', fb: 'travelcheapkr' },
    topic: '특가 항공/숙소',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '연합 산업/여행', url: 'https://www.yna.co.kr/rss/industry.xml' },
    ],
    format: 'card',
    cardTemplate: 'tpl-travel-boardingpass',
    palette: ['#0E3A5F', '#FFC24B', '#EAF4FB'],
    typeface: 'Pretendard',
    tone: '설레지만 실용. 정가 대비 절감액을 항상 병기. 존댓말.',
    hookPattern: '가격 대비 시각화 (예: "도쿄 왕복 19만원 — 정가 대비 -42%")',
    ctaPattern: '"특가 알림 받기 → 팔로우"',
    postsPerDay: 15,
    bestHours: [8, 12, 13, 20, 22],
  },
  {
    slug: 'law-life',
    handle: { ig: '@law.life.kr', fb: 'lawlifekr' },
    topic: '생활 법률',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '한겨레 사회', url: 'https://www.hani.co.kr/rss/society/' },
    ],
    format: 'card',
    cardTemplate: 'tpl-law-document-navy',
    palette: ['#12233B', '#B7975A', '#F4F1EA'],
    typeface: 'GowunBatang',
    tone: '신뢰감 있는 정보 전달. 단정 법률자문 금지, "참고용·전문가 상담 권고" 고지 필수.',
    hookPattern: '"이거 모르면 손해" (예: "전세 계약 이 한 줄 없으면 보증금 못 받습니다")',
    ctaPattern: '"저장해두고 계약 전 확인 → 팔로우"',
    postsPerDay: 15,
    bestHours: [8, 12, 19, 21, 22],
  },
  {
    slug: 'job-market',
    handle: { ig: '@job.market.kr', fb: 'jobmarketkr' },
    topic: '채용/연봉',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '연합 경제', url: 'https://www.yna.co.kr/rss/economy.xml' },
    ],
    format: 'card',
    cardTemplate: 'tpl-job-chart-clean',
    palette: ['#101826', '#3B82F6', '#EEF3FA'],
    typeface: 'Pretendard',
    tone: '데이터 기반 커리어 코치. 분포·그래프 중심. 존댓말.',
    hookPattern: '연봉 분포 그래프 (예: "3년차 개발자 연봉 중앙값, 생각보다 낮다")',
    ctaPattern: '"내 연봉 위치 저장 → 협상 카드로"',
    postsPerDay: 15,
    bestHours: [8, 12, 18, 20, 22],
  },
  {
    slug: 'study-hack',
    handle: { ig: '@study.hack.kr', fb: 'studyhackkr' },
    topic: '공부법/시험',
    sources: [
      { type: 'reddit_json', label: 'r/GetStudying', params: { subreddit: 'GetStudying', sort: 'hot' } },
      GT('KR'),
    ],
    format: 'reel',
    cardTemplate: 'tpl-study-timer-pastel',
    palette: ['#FFF9F0', '#FF8A5B', '#3A2E2A'],
    typeface: 'Pretendard',
    tone: '동기부여형 스터디메이트. 타이머·체크리스트 비주얼. 친근한 존댓말.',
    hookPattern: '타이머 비주얼 (예: "25분만 이렇게 — 집중력 2배")',
    ctaPattern: '"오늘 공부 인증 댓글 → 같이 달리기"',
    postsPerDay: 15,
    bestHours: [7, 9, 15, 20, 23],
  },
  {
    slug: 'game-meta',
    handle: { ig: '@game.meta.kr', fb: 'gamemetakr' },
    topic: '게임 패치/메타',
    sources: [
      { type: 'reddit_json', label: 'r/gaming', params: { subreddit: 'gaming', sort: 'hot' } },
      { type: 'youtube_popular', label: 'YouTube 게임 인기', params: { categoryId: '20', regionCode: 'KR' } },
    ],
    format: 'card',
    cardTemplate: 'tpl-game-tierlist',
    palette: ['#0C0F1A', '#E23B5A', '#F1D06B'],
    typeface: 'Pretendard',
    tone: '게이머 커뮤니티 톤. 티어·버프/너프 직관 표. 간결.',
    hookPattern: '티어표 변동 (예: "이번 패치로 1티어 뒤집혔다")',
    ctaPattern: '"내 주력 챔프 댓글 → 티어 분석"',
    postsPerDay: 15,
    bestHours: [13, 17, 20, 22, 23],
  },
  {
    slug: 'sports-brief',
    handle: { ig: '@sports.brief.kr', fb: 'sportsbriefkr' },
    topic: '스포츠 결과/기록',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '한겨레 스포츠', url: 'https://www.hani.co.kr/rss/sports/' },
    ],
    format: 'card',
    cardTemplate: 'tpl-sports-scoreboard',
    palette: ['#0A1A2F', '#22C55E', '#F8FAFC'],
    typeface: 'Pretendard',
    tone: '중계 캐스터 톤. 스코어·기록 대비 명확. 존댓말.',
    hookPattern: '스코어 대비 (예: "9회말 역전 — 이 한 타석이 경기를 바꿨다")',
    ctaPattern: '"오늘 경기 결과 저장 → 팔로우"',
    postsPerDay: 15,
    bestHours: [7, 8, 22, 23, 0],
  },
  {
    slug: 'k-culture',
    handle: { ig: '@k.culture.kr', fb: 'kculturekr' },
    topic: 'K팝/드라마 이슈',
    sources: [
      GT('KR'),
      { type: 'reddit_json', label: 'r/kpop', params: { subreddit: 'kpop', sort: 'hot' } },
    ],
    format: 'reel',
    cardTemplate: 'tpl-kculture-vivid',
    palette: ['#160D1F', '#FF4FA3', '#FDE7F3'],
    typeface: 'Pretendard',
    tone: '팬 감성 + 이슈 정리. 반응 인용형. 확인 안 된 루머 배제.',
    hookPattern: '반응 인용형 (예: "이 무대 실화? 댓글 폭발한 이유")',
    ctaPattern: '"최애 태그하고 공유 → 다음 이슈 알림"',
    postsPerDay: 15,
    bestHours: [12, 16, 19, 21, 23],
  },
  {
    slug: 'parenting',
    handle: { ig: '@parenting.kr', fb: 'parentingkr' },
    topic: '육아 정보',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '한겨레 사회', url: 'https://www.hani.co.kr/rss/society/' },
    ],
    format: 'card',
    cardTemplate: 'tpl-parenting-soft-checklist',
    palette: ['#FFF6F2', '#F6A17A', '#4A3B34'],
    typeface: 'Pretendard',
    tone: '공감형 선배맘. 단정 의료조언 금지, "참고용·전문의 상담" 고지. 따뜻한 존댓말.',
    hookPattern: '월령별 체크리스트 (예: "돌 전 이건 꼭 — 놓치기 쉬운 3가지")',
    ctaPattern: '"우리 아이 월령 저장 → 체크리스트 받기"',
    postsPerDay: 15,
    bestHours: [6, 10, 13, 21, 22],
  },
  {
    slug: 'pet-care',
    handle: { ig: '@pet.care.kr', fb: 'petcarekr' },
    topic: '반려동물',
    sources: [
      { type: 'reddit_json', label: 'r/dogs', params: { subreddit: 'dogs', sort: 'hot' } },
      { type: 'reddit_json', label: 'r/cats', params: { subreddit: 'cats', sort: 'hot' } },
    ],
    format: 'reel',
    cardTemplate: 'tpl-pet-warm-round',
    palette: ['#FFF8EE', '#E8A23D', '#3E2F1C'],
    typeface: 'Pretendard',
    tone: '다정한 집사/견주 톤. 단정 진단 금지, "이상 시 병원" 고지. 존댓말.',
    hookPattern: '증상 → 원인 (예: "강아지가 발을 자꾸 핥으면 이 신호")',
    ctaPattern: '"우리 아이 증상 댓글 → 체크포인트 공유"',
    postsPerDay: 15,
    bestHours: [8, 12, 18, 21, 22],
  },
  {
    slug: 'home-diy',
    handle: { ig: '@home.diy.kr', fb: 'homediykr' },
    topic: '자취/살림 팁',
    sources: [
      { type: 'reddit_json', label: 'r/lifehacks', params: { subreddit: 'lifehacks', sort: 'hot' } },
      GT('KR'),
    ],
    format: 'card',
    cardTemplate: 'tpl-diy-beforeafter',
    palette: ['#F5F3EF', '#2FA6A0', '#22312F'],
    typeface: 'Pretendard',
    tone: '실전 살림꾼. before/after 대비 강조. 간결한 존댓말.',
    hookPattern: 'before/after (예: "3,000원으로 바뀐 자취방 — 전후 비교")',
    ctaPattern: '"따라 하고 인증 → 다음 꿀팁 저장"',
    postsPerDay: 15,
    bestHours: [10, 13, 19, 21, 22],
  },
  {
    slug: 'eco-life',
    handle: { ig: '@eco.life.kr', fb: 'ecolifekr' },
    topic: '환경/절약',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '한겨레 환경', url: 'https://www.hani.co.kr/rss/society/' },
    ],
    format: 'card',
    cardTemplate: 'tpl-eco-leaf-earth',
    palette: ['#F2F7EF', '#4C9A2A', '#1E3016'],
    typeface: 'Pretendard',
    tone: '실용 절약형 환경 코치. 절약 금액 환산 강조. 존댓말.',
    hookPattern: '절약 금액 환산 (예: "대기전력만 껐는데 연 6만원 절약")',
    ctaPattern: '"이번 달 절약 인증 → 같이 실천"',
    postsPerDay: 15,
    bestHours: [8, 12, 18, 20, 22],
  },
  {
    slug: 'psychology',
    handle: { ig: '@psychology.kr', fb: 'psychologykr' },
    topic: '심리/관계',
    sources: [
      { type: 'reddit_json', label: 'r/psychology', params: { subreddit: 'psychology', sort: 'hot' } },
      { type: 'reddit_json', label: 'r/relationship_advice', params: { subreddit: 'relationship_advice', sort: 'top', t: 'day' } },
    ],
    format: 'card',
    cardTemplate: 'tpl-psych-question-mono',
    palette: ['#141018', '#9B8CFF', '#EFEAF7'],
    typeface: 'GowunBatang',
    tone: '차분한 상담가 톤. 단정 진단 금지, "재미/참고용" 고지. 질문으로 끌어들이기.',
    hookPattern: '질문형 후킹 (예: "왜 읽씹에 더 신경 쓰일까?")',
    ctaPattern: '"내 얘기 같으면 저장 → 관계 인사이트"',
    postsPerDay: 15,
    bestHours: [12, 18, 21, 22, 23],
  },
  {
    slug: 'history-1min',
    handle: { ig: '@history.1min.kr', fb: 'history1minkr' },
    topic: '역사 상식',
    sources: [
      { type: 'reddit_json', label: 'r/history', params: { subreddit: 'history', sort: 'top', t: 'day' } },
      { type: 'reddit_json', label: 'r/todayilearned', params: { subreddit: 'todayilearned', sort: 'hot' } },
    ],
    format: 'reel',
    cardTemplate: 'tpl-history-parchment',
    palette: ['#1C160E', '#C99A48', '#F3E9D2'],
    typeface: 'GowunBatang',
    tone: '흥미로운 이야기꾼. 사실 검증 중시, 출처 명시. 존댓말.',
    hookPattern: '"오늘 이날" (예: "1950년 오늘, 이 결정이 역사를 바꿨다")',
    ctaPattern: '"오늘의 역사 매일 → 팔로우"',
    postsPerDay: 15,
    bestHours: [7, 12, 19, 21, 22],
  },
  {
    slug: 'policy-alert',
    handle: { ig: '@policy.alert.kr', fb: 'policyalertkr' },
    topic: '정부지원/정책',
    sources: [
      GT('KR'),
      { type: 'rss_news', label: '연합 사회/정책', url: 'https://www.yna.co.kr/rss/society.xml' },
    ],
    format: 'card',
    cardTemplate: 'tpl-policy-official-badge',
    palette: ['#0E2A47', '#2FB4C8', '#EAF6F9'],
    typeface: 'Pretendard',
    tone: '공공정보 안내체. 신청 마감·자격요건 명확. 단정 금지, 공식 출처 링크. 존댓말.',
    hookPattern: '신청 마감일 카운트다운 (예: "청년월세 지원 D-7 — 놓치면 1년 대기")',
    ctaPattern: '"신청 자격 저장 → 마감 알림 받기"',
    postsPerDay: 15,
    bestHours: [8, 9, 12, 18, 20],
  },
];

export const VERTICAL_BY_SLUG: Record<string, Vertical> = Object.fromEntries(
  VERTICALS.map((v) => [v.slug, v]),
);

export function getVertical(slug: string): Vertical {
  const v = VERTICAL_BY_SLUG[slug];
  if (!v) throw new Error(`알 수 없는 버티컬: ${slug}`);
  return v;
}
