-- =============================================================================
-- 덕메이트(DuckMate) · D1 마이그레이션 00005 — 시드 데이터
--   1) hobbies: 콜드스타트 카테고리(PRD §1-9 + 오픈이슈 9) 포함 70+ 태그
--   2) quiz_questions: A2 §4 — 5축 × 2문항, 4지선다 벡터 -1.0/-0.33/+0.33/+1.0,
--      meeting·intent 축 weight 1.2
--   3) quests: Phase 2 대비 기본 시드 (전부 is_active = false)
-- 멱등: hobbies/quests 는 on conflict do nothing, quiz 는 빈 테이블일 때만 삽입.
-- =============================================================================

-- 1. hobbies ------------------------------------------------------------------
insert into public.hobbies (slug, name, category, icon) values
  -- 게임
  ('valorant',        '발로란트',        '게임', '🎯'),
  ('genshin',         '원신',            '게임', '⚔️'),
  ('lol',             '리그오브레전드',  '게임', '🕹️'),
  ('overwatch',       '오버워치',        '게임', '🛡️'),
  ('steam-games',     '스팀게임',        '게임', '💻'),
  ('nintendo',        '닌텐도 스위치',   '게임', '🎮'),
  ('mobile-games',    '모바일게임',      '게임', '📱'),
  ('minecraft',       '마인크래프트',    '게임', '⛏️'),
  ('rhythm-games',    '리듬게임',        '게임', '🎵'),
  ('retro-games',     '레트로게임',      '게임', '👾'),
  -- 애니·웹툰
  ('anime',           '애니메이션',      '애니·웹툰', '🎬'),
  ('webtoon',         '웹툰',            '애니·웹툰', '📱'),
  ('manga',           '만화·망가',       '애니·웹툰', '📚'),
  ('vtuber',          '버튜버',          '애니·웹툰', '🎤'),
  ('cosplay',         '코스프레',        '애니·웹툰', '🎭'),
  ('figure',          '피규어·굿즈',     '애니·웹툰', '🧸'),
  ('light-novel',     '라이트노벨',      '애니·웹툰', '📖'),
  ('ani-song',        '애니송·J-POP',    '애니·웹툰', '🎶'),
  -- 아이돌·팬덤
  ('kpop-idol',       'K-POP 아이돌',    '아이돌·팬덤', '💜'),
  ('concert-going',   '콘서트 원정',     '아이돌·팬덤', '🎫'),
  ('fan-goods',       '팬굿즈 수집',     '아이돌·팬덤', '📿'),
  ('popup-store',     '팝업스토어 투어', '아이돌·팬덤', '🏬'),
  ('homemaster',      '홈마·직캠',       '아이돌·팬덤', '📸'),
  ('jpop-idol',       'J-POP·해외 아이돌', '아이돌·팬덤', '🌟'),
  -- 스포츠·러닝·클라이밍
  ('running',         '러닝',            '스포츠', '🏃'),
  ('climbing',        '클라이밍',        '스포츠', '🧗'),
  ('hiking',          '등산',            '스포츠', '⛰️'),
  ('gym',             '헬스·웨이트',     '스포츠', '💪'),
  ('swimming',        '수영',            '스포츠', '🏊'),
  ('tennis',          '테니스',          '스포츠', '🎾'),
  ('badminton',       '배드민턴',        '스포츠', '🏸'),
  ('cycling',         '자전거',          '스포츠', '🚴'),
  ('futsal',          '풋살·축구',       '스포츠', '⚽'),
  ('bowling',         '볼링',            '스포츠', '🎳'),
  ('yoga',            '요가·필라테스',   '스포츠', '🧘'),
  ('baseball-fan',    '야구 직관',       '스포츠', '⚾'),
  -- 보드게임
  ('boardgame',       '보드게임',        '보드게임', '🎲'),
  ('escape-room',     '방탈출',          '보드게임', '🗝️'),
  ('trpg',            'TRPG',            '보드게임', '🐉'),
  ('chess-baduk',     '체스·바둑',       '보드게임', '♟️'),
  ('puzzle',          '퍼즐',            '보드게임', '🧩'),
  -- 카페·맛집
  ('cafe-tour',       '카페투어',        '카페·맛집', '☕'),
  ('matzip-tour',     '맛집투어',        '카페·맛집', '🍜'),
  ('dessert',         '디저트·베이킹',   '카페·맛집', '🍰'),
  ('coffee-brewing',  '커피·홈카페',     '카페·맛집', '🫖'),
  ('wine-tasting',    '와인·전통주',     '카페·맛집', '🍷'),
  ('cooking',         '요리',            '카페·맛집', '🍳'),
  -- 공연·전시
  ('musical',         '뮤지컬',          '공연·전시', '🎭'),
  ('theater',         '연극',            '공연·전시', '🎪'),
  ('exhibition',      '전시·미술관',     '공연·전시', '🖼️'),
  ('indie-concert',   '인디 공연',       '공연·전시', '🎸'),
  ('classic-concert', '클래식 공연',     '공연·전시', '🎻'),
  ('festival',        '페스티벌',        '공연·전시', '🎪'),
  ('movie',           '영화·시네필',     '공연·전시', '🎥'),
  -- 사진·영상
  ('photography',     '사진 촬영',       '사진·영상', '📷'),
  ('film-camera',     '필름카메라',      '사진·영상', '🎞️'),
  ('vlog',            '브이로그·영상편집', '사진·영상', '🎦'),
  ('drawing',         '드로잉·일러스트', '사진·영상', '🎨'),
  -- 코딩·테크
  ('coding',          '코딩·사이드프로젝트', '코딩·테크', '⌨️'),
  ('ai-tools',        'AI 도구 탐구',    '코딩·테크', '🤖'),
  ('mech-keyboard',   '기계식 키보드',   '코딩·테크', '⌨️'),
  ('gadget',          '가젯·전자기기',   '코딩·테크', '🔌'),
  ('hackathon',       '해커톤·메이커',   '코딩·테크', '🛠️'),
  -- 독서·글쓰기
  ('reading',         '독서',            '독서·글쓰기', '📚'),
  ('book-club',       '독서모임',        '독서·글쓰기', '👥'),
  ('writing',         '글쓰기·창작',     '독서·글쓰기', '✍️'),
  ('sf-mystery',      'SF·추리소설',     '독서·글쓰기', '🔍'),
  ('poetry',          '시·에세이',       '독서·글쓰기', '🖋️'),
  -- 음악
  ('band',            '밴드·합주',       '음악', '🥁'),
  ('instrument',      '악기 연주',       '음악', '🎹'),
  ('vinyl',           'LP·바이닐 수집',  '음악', '💿'),
  ('noraebang',       '노래방',          '음악', '🎤'),
  ('hiphop',          '힙합·랩',         '음악', '🎧'),
  -- 여행·아웃도어
  ('travel',          '국내여행',        '여행·아웃도어', '🧳'),
  ('overseas-travel', '해외여행',        '여행·아웃도어', '✈️'),
  ('camping',         '캠핑',            '여행·아웃도어', '🏕️'),
  ('picnic',          '피크닉·산책',     '여행·아웃도어', '🧺')
on conflict (slug) do nothing;

-- 2. quiz_questions (A2 §4 — 문항·축·가중치 그대로) ----------------------------
insert into public.quiz_questions (category, text, options, weight, sort_order)
select * from (values
  ('immersion',
   '새로운 취미가 생기면 나는?',
   '[{"label": "적당히 즐기는 편이 좋다",              "value": -1.0},
     {"label": "재미있으면 조금씩 더 찾아본다",        "value": -0.33},
     {"label": "관련 영상·커뮤니티를 정주행한다",      "value": 0.33},
     {"label": "굿즈·커뮤니티·기록까지 전부 판다",     "value": 1.0}]'::jsonb,
   1.00, 1),
  ('immersion',
   '좋아하는 걸 즐기는 내 방식은?',
   '[{"label": "보고 듣는 감상이 제일 좋다",           "value": -1.0},
     {"label": "감상 후 가끔 후기를 남긴다",           "value": -0.33},
     {"label": "기록·리뷰를 꾸준히 쌓는다",            "value": 0.33},
     {"label": "2차 창작·제작까지 직접 한다",          "value": 1.0}]'::jsonb,
   1.00, 2),
  ('meeting',
   '취향 맞는 사람이 생기면 먼저 하고 싶은 건?',
   '[{"label": "밤새 채팅으로 수다",                   "value": -1.0},
     {"label": "일단 온라인으로 친해지기",             "value": -0.33},
     {"label": "시간 맞으면 만나기",                   "value": 0.33},
     {"label": "주말에 바로 만나기",                   "value": 1.0}]'::jsonb,
   1.20, 3),
  ('meeting',
   '취미를 함께할 때 더 편한 쪽은?',
   '[{"label": "단둘이 깊게 이야기",                   "value": -1.0},
     {"label": "친한 소수와 조용히",                   "value": -0.33},
     {"label": "소모임 정도가 딱 좋다",                "value": 0.33},
     {"label": "여럿이 왁자지껄",                      "value": 1.0}]'::jsonb,
   1.20, 4),
  ('tempo',
   '메시지를 받으면 나는?',
   '[{"label": "보는 즉시 바로 답장",                  "value": -1.0},
     {"label": "웬만하면 빨리 답한다",                 "value": -0.33},
     {"label": "하던 일 끝내고 답한다",                "value": 0.33},
     {"label": "여유 있을 때 몰아서 답한다",           "value": 1.0}]'::jsonb,
   1.00, 5),
  ('tempo',
   '대화할 때 나는?',
   '[{"label": "내 얘기를 쏟아내는 편",                "value": -1.0},
     {"label": "말하는 쪽이 조금 더 편하다",           "value": -0.33},
     {"label": "듣는 쪽이 조금 더 편하다",             "value": 0.33},
     {"label": "상대 얘기를 듣는 게 제일 편하다",      "value": 1.0}]'::jsonb,
   1.00, 6),
  ('explore',
   '취미를 대하는 나는?',
   '[{"label": "하나를 오래, 깊게 판다",               "value": -1.0},
     {"label": "주력 하나 + 곁가지 조금",              "value": -0.33},
     {"label": "몇 개를 돌아가며 즐긴다",              "value": 0.33},
     {"label": "새로운 걸 계속 시도한다",              "value": 1.0}]'::jsonb,
   1.00, 7),
  ('explore',
   '주말 활동 스타일은?',
   '[{"label": "미리 예매하고 코스까지 짠다",          "value": -1.0},
     {"label": "큰 틀만 정해두는 편",                  "value": -0.33},
     {"label": "전날 기분 따라 정한다",                "value": 0.33},
     {"label": "그날 끌리는 대로 움직인다",            "value": 1.0}]'::jsonb,
   1.00, 8),
  ('intent',
   '덕메이트에서 기대하는 건?',
   '[{"label": "취미 얘기할 덕메·활동 메이트",         "value": -1.0},
     {"label": "우선 친구, 그 이상은 천천히",          "value": -0.33},
     {"label": "친구로 시작해 잘 맞으면 연애도",       "value": 0.33},
     {"label": "잘 맞는 사람과의 연애",                "value": 1.0}]'::jsonb,
   1.20, 9),
  ('intent',
   '마음이 가는 사람이 생기면?',
   '[{"label": "오래 알아가고 확신이 서야 한다",       "value": -1.0},
     {"label": "천천히, 신호를 쌓아가며",              "value": -0.33},
     {"label": "어느 정도 통하면 표현한다",            "value": 0.33},
     {"label": "느낌이 오면 바로 표현한다",            "value": 1.0}]'::jsonb,
   1.20, 10)
) as seed(category, text, options, weight, sort_order)
where not exists (select 1 from public.quiz_questions);

-- 3. quests — Phase 2 대비 기본 시드 (스펙 §5-5 · 전부 비활성) -----------------
insert into public.quests (key, title, kind, reward, is_active) values
  ('daily_login',      '오늘 접속하기',                'daily',
   '{"type": "xp", "qty": 10}'::jsonb, false),
  ('daily_card_check', '오늘의 궁합 카드 확인',        'daily',
   '{"type": "xp", "qty": 10}'::jsonb, false),
  ('daily_vote',       '취향 배틀 1회 참여',           'daily',
   '{"type": "xp", "qty": 15}'::jsonb, false),
  ('daily_reply',      '대화에 답장하기',              'daily',
   '{"type": "xp", "qty": 15}'::jsonb, false),
  ('weekly_streak_7',  '7일 연속 접속',                'weekly',
   '{"type": "item", "item_type": "superlike", "qty": 1, "expires_days": 30}'::jsonb, false),
  ('weekly_battle_3',  '이번 주 취향 배틀 3회',        'weekly',
   '{"type": "xp", "qty": 50}'::jsonb, false),
  ('weekly_new_talk',  '새 매칭 상대와 10턴 대화',     'weekly',
   '{"type": "xp", "qty": 50}'::jsonb, false),
  ('profile_complete', '덕질카드 완성하기 (최애·요즘 빠진 것)', 'daily',
   '{"type": "xp", "qty": 20}'::jsonb, false)
on conflict (key) do nothing;
