/**
 * 내장 시드 규칙 — 키워드 휴리스틱 (신뢰도 0.5).
 *
 * 파이프라인의 마지막 단계다. 사용자 규칙도 전역 사전도 못 맞힌 상호명을
 * 상호명만 보고 추정한다.
 *
 * [규칙 작성 원칙]
 * 1. 긴 키워드가 이긴다. "동물병원"(4자)이 "병원"(2자)보다 먼저 매칭되므로
 *    같은 문자열을 담은 상·하위 개념을 따로 신경 쓰지 않아도 된다.
 * 2. 짧고 흔한 조각은 넣지 않는다. "펫"은 "카펫"에, "이자"는 "이자카야"에,
 *    "짐"은 "이삿짐"에 걸린다. 오분류는 미분류보다 나쁘다.
 * 3. 영문 약어처럼 다른 단어에 파묻히기 쉬운 키워드는 prefix 로 잠근다.
 *    "CU"는 contains 로 두면 "DOCUMENT"에 걸린다.
 */
import type { SeedRule } from './types.js';

/** contains 기본. prefix 는 상호명이 그 토큰으로 시작할 때만 매칭한다. */
const rule = (keyword: string, categoryKey: string, mode?: 'prefix'): SeedRule =>
  mode ? { keyword, categoryKey, mode } : { keyword, categoryKey, mode: 'contains' };

export const SEED_RULES: readonly SeedRule[] = [
  /* ── 카페·음료 ─────────────────────────────────────────────────────────── */
  rule('스타벅스', 'food.cafe'),
  rule('STARBUCKS', 'food.cafe'),
  rule('투썸플레이스', 'food.cafe'),
  rule('투썸', 'food.cafe'),
  rule('이디야', 'food.cafe'),
  rule('메가커피', 'food.cafe'),
  rule('메가엠지씨', 'food.cafe'),
  rule('빽다방', 'food.cafe'),
  rule('컴포즈커피', 'food.cafe'),
  rule('커피빈', 'food.cafe'),
  rule('폴바셋', 'food.cafe'),
  rule('할리스', 'food.cafe'),
  rule('파스쿠찌', 'food.cafe'),
  rule('탐앤탐스', 'food.cafe'),
  rule('엔젤리너스', 'food.cafe'),
  rule('블루보틀', 'food.cafe'),
  rule('더벤티', 'food.cafe'),
  rule('매머드커피', 'food.cafe'),
  rule('공차', 'food.cafe'),
  rule('쥬씨', 'food.cafe'),
  rule('배스킨라빈스', 'food.cafe'),
  rule('설빙', 'food.cafe'),
  rule('던킨', 'food.cafe'),
  rule('파리바게뜨', 'food.cafe'),
  rule('뚜레쥬르', 'food.cafe'),
  rule('커피', 'food.cafe'),
  rule('카페', 'food.cafe'),
  rule('COFFEE', 'food.cafe'),

  /* ── 배달 ──────────────────────────────────────────────────────────────── */
  rule('배달의민족', 'food.delivery'),
  rule('배민', 'food.delivery'),
  rule('요기요', 'food.delivery'),
  rule('쿠팡이츠', 'food.delivery'),
  rule('땡겨요', 'food.delivery'),
  rule('BAEMIN', 'food.delivery'),

  /* ── 편의점 ────────────────────────────────────────────────────────────── */
  rule('GS25', 'food.convenience'),
  rule('세븐일레븐', 'food.convenience'),
  rule('7ELEVEN', 'food.convenience'),
  rule('이마트24', 'food.convenience'),
  rule('미니스톱', 'food.convenience'),
  rule('편의점', 'food.convenience'),
  rule('씨유', 'food.convenience'),
  // "CU"는 다른 영문 단어에 파묻히기 쉬워 상호명 첫머리에서만 인정한다.
  rule('CU', 'food.convenience', 'prefix'),

  /* ── 외식 ──────────────────────────────────────────────────────────────── */
  rule('맥도날드', 'food.dining'),
  rule('버거킹', 'food.dining'),
  rule('롯데리아', 'food.dining'),
  rule('맘스터치', 'food.dining'),
  rule('노브랜드버거', 'food.dining'),
  rule('서브웨이', 'food.dining'),
  rule('피자헛', 'food.dining'),
  rule('도미노피자', 'food.dining'),
  rule('미스터피자', 'food.dining'),
  rule('김밥천국', 'food.dining'),
  rule('한솥도시락', 'food.dining'),
  rule('본죽', 'food.dining'),
  rule('놀부', 'food.dining'),
  rule('새마을식당', 'food.dining'),
  rule('명륜진사갈비', 'food.dining'),
  rule('하남돼지집', 'food.dining'),
  rule('원할머니', 'food.dining'),
  rule('아웃백', 'food.dining'),
  rule('애슐리', 'food.dining'),
  rule('VIPS', 'food.dining'),
  rule('교촌치킨', 'food.dining'),
  rule('BBQ', 'food.dining'),
  rule('bhc', 'food.dining'),
  rule('굽네치킨', 'food.dining'),
  rule('처갓집', 'food.dining'),
  rule('네네치킨', 'food.dining'),
  rule('KFC', 'food.dining'),
  rule('이자카야', 'food.dining'),
  rule('식당', 'food.dining'),
  rule('분식', 'food.dining'),
  rule('국밥', 'food.dining'),
  rule('칼국수', 'food.dining'),
  rule('삼겹살', 'food.dining'),

  /* ── 장보기 ────────────────────────────────────────────────────────────── */
  rule('이마트에브리데이', 'food.grocery'),
  rule('홈플러스', 'food.grocery'),
  rule('롯데마트', 'food.grocery'),
  rule('코스트코', 'food.grocery'),
  rule('COSTCO', 'food.grocery'),
  rule('하나로마트', 'food.grocery'),
  rule('노브랜드', 'food.grocery'),
  rule('마켓컬리', 'food.grocery'),
  rule('컬리', 'food.grocery'),
  rule('오아시스마켓', 'food.grocery'),
  rule('이마트', 'food.grocery'),
  rule('농협하나로', 'food.grocery'),
  rule('정육점', 'food.grocery'),
  rule('청과', 'food.grocery'),

  /* ── 대중교통 ──────────────────────────────────────────────────────────── */
  rule('코레일', 'transport.transit'),
  rule('KORAIL', 'transport.transit'),
  rule('SRT', 'transport.transit'),
  // KTX 는 통신사 KT 규칙(prefix)보다 길어서 먼저 매칭된다. 순서가 아니라 길이가 지킨다.
  rule('KTX', 'transport.transit'),
  rule('티머니', 'transport.transit'),
  rule('캐시비', 'transport.transit'),
  rule('레일플러스', 'transport.transit'),
  rule('지하철', 'transport.transit'),
  rule('고속버스', 'transport.transit'),
  rule('시외버스', 'transport.transit'),
  rule('버스', 'transport.transit'),
  rule('철도', 'transport.transit'),

  /* ── 택시 ──────────────────────────────────────────────────────────────── */
  rule('카카오T', 'transport.taxi'),
  rule('카카오택시', 'transport.taxi'),
  rule('타다', 'transport.taxi'),
  rule('우버', 'transport.taxi'),
  rule('UBER', 'transport.taxi'),
  rule('아이엠택시', 'transport.taxi'),
  rule('택시', 'transport.taxi'),

  /* ── 주유 ──────────────────────────────────────────────────────────────── */
  rule('SK에너지', 'transport.fuel'),
  rule('GS칼텍스', 'transport.fuel'),
  rule('S-OIL', 'transport.fuel'),
  rule('에쓰오일', 'transport.fuel'),
  rule('현대오일뱅크', 'transport.fuel'),
  rule('오일뱅크', 'transport.fuel'),
  rule('주유소', 'transport.fuel'),
  rule('셀프주유', 'transport.fuel'),
  rule('충전소', 'transport.fuel'),

  /* ── 주차·통행료 ───────────────────────────────────────────────────────── */
  rule('하이패스', 'transport.parking'),
  rule('한국도로공사', 'transport.parking'),
  rule('아이파킹', 'transport.parking'),
  rule('파킹클라우드', 'transport.parking'),
  rule('모두의주차장', 'transport.parking'),
  rule('주차장', 'transport.parking'),
  rule('주차', 'transport.parking'),

  /* ── 주거 ──────────────────────────────────────────────────────────────── */
  rule('관리비', 'home.rent'),
  rule('월세', 'home.rent'),
  rule('임대료', 'home.rent'),
  rule('한국전력', 'home.utility'),
  rule('전기요금', 'home.utility'),
  rule('도시가스', 'home.utility'),
  rule('지역난방', 'home.utility'),
  rule('상수도', 'home.utility'),
  rule('수도요금', 'home.utility'),

  /* ── 통신 ──────────────────────────────────────────────────────────────── */
  rule('SK텔레콤', 'home.telecom'),
  rule('SKT', 'home.telecom'),
  rule('LG유플러스', 'home.telecom'),
  rule('유플러스', 'home.telecom'),
  rule('헬로모바일', 'home.telecom'),
  rule('알뜰폰', 'home.telecom'),
  rule('통신요금', 'home.telecom'),
  rule('인터넷요금', 'home.telecom'),
  rule('KT', 'home.telecom', 'prefix'),

  /* ── 온라인쇼핑 ────────────────────────────────────────────────────────── */
  rule('쿠팡', 'shopping.online'),
  rule('COUPANG', 'shopping.online'),
  rule('11번가', 'shopping.online'),
  rule('G마켓', 'shopping.online'),
  rule('지마켓', 'shopping.online'),
  rule('옥션', 'shopping.online'),
  rule('위메프', 'shopping.online'),
  rule('티몬', 'shopping.online'),
  rule('스마트스토어', 'shopping.online'),
  rule('네이버페이', 'shopping.online'),
  rule('인터파크', 'shopping.online'),
  rule('SSG닷컴', 'shopping.online'),
  rule('알리익스프레스', 'shopping.online'),
  rule('ALIEXPRESS', 'shopping.online'),
  rule('AMAZON', 'shopping.online'),
  rule('무신사', 'shopping.online'),
  rule('에이블리', 'shopping.online'),
  rule('지그재그', 'shopping.online'),
  rule('29CM', 'shopping.online'),
  rule('오늘의집', 'shopping.online'),

  /* ── 의류·패션 ─────────────────────────────────────────────────────────── */
  rule('유니클로', 'shopping.fashion'),
  rule('UNIQLO', 'shopping.fashion'),
  rule('ZARA', 'shopping.fashion'),
  rule('탑텐', 'shopping.fashion'),
  rule('스파오', 'shopping.fashion'),
  rule('나이키', 'shopping.fashion'),
  rule('NIKE', 'shopping.fashion'),
  rule('아디다스', 'shopping.fashion'),
  rule('ADIDAS', 'shopping.fashion'),
  rule('뉴발란스', 'shopping.fashion'),
  rule('데상트', 'shopping.fashion'),
  rule('노스페이스', 'shopping.fashion'),
  rule('디스커버리', 'shopping.fashion'),
  rule('ABC마트', 'shopping.fashion'),
  rule('슈마커', 'shopping.fashion'),

  /* ── 뷰티·미용 ─────────────────────────────────────────────────────────── */
  rule('올리브영', 'shopping.beauty'),
  rule('아리따움', 'shopping.beauty'),
  rule('이니스프리', 'shopping.beauty'),
  rule('시코르', 'shopping.beauty'),
  rule('네이처리퍼블릭', 'shopping.beauty'),
  rule('더페이스샵', 'shopping.beauty'),
  rule('미용실', 'shopping.beauty'),
  rule('헤어샵', 'shopping.beauty'),
  rule('네일샵', 'shopping.beauty'),
  rule('피부관리', 'shopping.beauty'),

  /* ── 가전·디지털 ───────────────────────────────────────────────────────── */
  rule('하이마트', 'shopping.electronics'),
  rule('전자랜드', 'shopping.electronics'),
  rule('애플스토어', 'shopping.electronics'),
  rule('APPLESTORE', 'shopping.electronics'),
  rule('삼성전자', 'shopping.electronics'),
  rule('LG전자', 'shopping.electronics'),
  rule('컴퓨존', 'shopping.electronics'),
  rule('다나와', 'shopping.electronics'),

  /* ── 생활용품 ──────────────────────────────────────────────────────────── */
  rule('다이소', 'shopping.household'),
  rule('아성다이소', 'shopping.household'),
  rule('무인양품', 'shopping.household'),
  rule('MUJI', 'shopping.household'),
  rule('이케아', 'shopping.household'),
  rule('IKEA', 'shopping.household'),
  rule('철물점', 'shopping.household'),
  rule('세탁소', 'shopping.household'),

  /* ── 구독 ──────────────────────────────────────────────────────────────── */
  rule('넷플릭스', 'leisure.subscription'),
  rule('NETFLIX', 'leisure.subscription'),
  rule('유튜브프리미엄', 'leisure.subscription'),
  rule('YOUTUBE', 'leisure.subscription'),
  rule('왓챠', 'leisure.subscription'),
  rule('웨이브', 'leisure.subscription'),
  rule('WAVVE', 'leisure.subscription'),
  rule('티빙', 'leisure.subscription'),
  rule('TVING', 'leisure.subscription'),
  rule('디즈니플러스', 'leisure.subscription'),
  rule('DISNEY', 'leisure.subscription'),
  rule('쿠팡플레이', 'leisure.subscription'),
  rule('멜론', 'leisure.subscription'),
  rule('MELON', 'leisure.subscription'),
  rule('지니뮤직', 'leisure.subscription'),
  rule('스포티파이', 'leisure.subscription'),
  rule('SPOTIFY', 'leisure.subscription'),
  rule('애플뮤직', 'leisure.subscription'),
  rule('아이클라우드', 'leisure.subscription'),
  rule('ICLOUD', 'leisure.subscription'),
  rule('GOOGLEONE', 'leisure.subscription'),
  rule('CHATGPT', 'leisure.subscription'),
  rule('OPENAI', 'leisure.subscription'),
  rule('NOTION', 'leisure.subscription'),
  rule('ADOBE', 'leisure.subscription'),
  rule('MICROSOFT', 'leisure.subscription'),

  /* ── 영화·공연 ─────────────────────────────────────────────────────────── */
  rule('CGV', 'leisure.movie'),
  rule('메가박스', 'leisure.movie'),
  rule('롯데시네마', 'leisure.movie'),
  rule('티켓링크', 'leisure.movie'),
  rule('예스24공연', 'leisure.movie'),

  /* ── 게임 ──────────────────────────────────────────────────────────────── */
  rule('STEAM', 'leisure.game'),
  rule('넥슨', 'leisure.game'),
  rule('NEXON', 'leisure.game'),
  rule('엔씨소프트', 'leisure.game'),
  rule('넷마블', 'leisure.game'),
  rule('배틀넷', 'leisure.game'),
  rule('플레이스테이션', 'leisure.game'),
  rule('PLAYSTATION', 'leisure.game'),
  rule('닌텐도', 'leisure.game'),
  rule('NINTENDO', 'leisure.game'),
  rule('구글플레이', 'leisure.game'),
  rule('GOOGLEPLAY', 'leisure.game'),
  rule('APPSTORE', 'leisure.game'),
  rule('PC방', 'leisure.game'),

  /* ── 도서 ──────────────────────────────────────────────────────────────── */
  rule('교보문고', 'leisure.book'),
  rule('YES24', 'leisure.book'),
  rule('예스24', 'leisure.book'),
  rule('알라딘', 'leisure.book'),
  rule('영풍문고', 'leisure.book'),
  rule('리디북스', 'leisure.book'),
  rule('밀리의서재', 'leisure.book'),
  rule('서점', 'leisure.book'),

  /* ── 여행·숙박 ─────────────────────────────────────────────────────────── */
  rule('야놀자', 'leisure.travel'),
  rule('여기어때', 'leisure.travel'),
  rule('아고다', 'leisure.travel'),
  rule('AGODA', 'leisure.travel'),
  rule('BOOKING', 'leisure.travel'),
  rule('에어비앤비', 'leisure.travel'),
  rule('AIRBNB', 'leisure.travel'),
  rule('호텔스컴바인', 'leisure.travel'),
  rule('하나투어', 'leisure.travel'),
  rule('모두투어', 'leisure.travel'),
  rule('대한항공', 'leisure.travel'),
  rule('아시아나', 'leisure.travel'),
  rule('제주항공', 'leisure.travel'),
  rule('진에어', 'leisure.travel'),
  rule('티웨이항공', 'leisure.travel'),
  rule('에어부산', 'leisure.travel'),
  rule('게스트하우스', 'leisure.travel'),
  rule('호텔', 'leisure.travel'),
  rule('펜션', 'leisure.travel'),

  /* ── 운동 ──────────────────────────────────────────────────────────────── */
  rule('헬스장', 'leisure.fitness'),
  rule('피트니스', 'leisure.fitness'),
  rule('필라테스', 'leisure.fitness'),
  rule('클라이밍', 'leisure.fitness'),
  rule('스크린골프', 'leisure.fitness'),
  rule('골프연습장', 'leisure.fitness'),
  rule('수영장', 'leisure.fitness'),
  rule('요가원', 'leisure.fitness'),

  /* ── 의료 ──────────────────────────────────────────────────────────────── */
  rule('동물병원', 'pet'),
  rule('정형외과', 'health.clinic'),
  rule('이비인후과', 'health.clinic'),
  rule('산부인과', 'health.clinic'),
  rule('한의원', 'health.clinic'),
  rule('피부과', 'health.clinic'),
  rule('안과', 'health.clinic'),
  rule('치과', 'health.clinic'),
  rule('내과', 'health.clinic'),
  rule('소아과', 'health.clinic'),
  rule('세브란스', 'health.clinic'),
  rule('아산병원', 'health.clinic'),
  rule('성모병원', 'health.clinic'),
  rule('병원', 'health.clinic'),
  rule('의원', 'health.clinic'),
  rule('온누리약국', 'health.pharmacy'),
  rule('약국', 'health.pharmacy'),

  /* ── 교육 ──────────────────────────────────────────────────────────────── */
  rule('메가스터디', 'education'),
  rule('이투스', 'education'),
  rule('대성마이맥', 'education'),
  rule('해커스', 'education'),
  rule('시원스쿨', 'education'),
  rule('파고다', 'education'),
  rule('클래스101', 'education'),
  rule('인프런', 'education'),
  rule('UDEMY', 'education'),
  rule('학원', 'education'),
  rule('교습소', 'education'),
  rule('등록금', 'education'),
  rule('수강료', 'education'),

  /* ── 보험·금융 ─────────────────────────────────────────────────────────── */
  rule('삼성생명', 'finance.insurance'),
  rule('삼성화재', 'finance.insurance'),
  rule('현대해상', 'finance.insurance'),
  rule('DB손해보험', 'finance.insurance'),
  rule('KB손해보험', 'finance.insurance'),
  rule('메리츠화재', 'finance.insurance'),
  rule('한화생명', 'finance.insurance'),
  rule('교보생명', 'finance.insurance'),
  rule('흥국화재', 'finance.insurance'),
  rule('롯데손해보험', 'finance.insurance'),
  rule('보험료', 'finance.insurance'),
  rule('실손보험', 'finance.insurance'),
  rule('대출이자', 'finance.loan'),
  rule('원리금', 'finance.loan'),
  rule('이자납입', 'finance.loan'),
  rule('송금수수료', 'finance.fee'),
  rule('연회비', 'finance.fee'),
  rule('수수료', 'finance.fee'),

  /* ── 경조사·선물 ───────────────────────────────────────────────────────── */
  rule('카카오톡선물하기', 'social'),
  rule('선물하기', 'social'),
  rule('기프티콘', 'social'),
  rule('축의금', 'social'),
  rule('부의금', 'social'),
  rule('조의금', 'social'),
  rule('경조사', 'social'),
  rule('화환', 'social'),

  /* ── 반려동물 ──────────────────────────────────────────────────────────── */
  rule('펫프렌즈', 'pet'),
  rule('어바웃펫', 'pet'),
  rule('하림펫푸드', 'pet'),
  rule('반려동물', 'pet'),
  rule('애견', 'pet'),
  rule('펫샵', 'pet'),

  /* ── 육아 ──────────────────────────────────────────────────────────────── */
  rule('아기용품', 'baby'),
  rule('유아용품', 'baby'),
  rule('기저귀', 'baby'),
  rule('분유', 'baby'),
  rule('베이비', 'baby'),
  rule('키즈카페', 'baby'),
  rule('어린이집', 'baby'),

  /* ── 수입 ──────────────────────────────────────────────────────────────── */
  rule('급여', 'income.salary'),
  rule('월급', 'income.salary'),
  rule('상여금', 'income.salary'),
  rule('성과급', 'income.salary'),
  rule('임금', 'income.salary'),
  rule('환급', 'income.refund'),
  rule('환불', 'income.refund'),
  rule('국세청', 'income.refund'),
  rule('연말정산', 'income.refund'),
  rule('예금이자', 'income.etc'),
  rule('배당금', 'income.etc'),
  rule('용돈', 'income.etc'),

  /* ── 이체 ──────────────────────────────────────────────────────────────── */
  rule('자동이체', 'transfer'),
  rule('계좌이체', 'transfer'),
  rule('송금', 'transfer'),
  rule('현금인출', 'transfer'),
  rule('ATM출금', 'transfer'),
];
