/**
 * 온보딩·인증 카피 상수 — 10_brand §4.5 확정본(#1~#13) + 12_flows §2 와이어 문구. 해요체, "탈락"·"회원님" 금지.
 * 서비스명은 리터럴 대신 SERVICE_NAME 만 참조한다(10_brand §0-1) — 소스는 E4 `config/company.ts`.
 */
import { NICKNAME_MAX, NICKNAME_MIN } from "@duckmate/db";
import { SERVICE_NAME } from "@/config/company";

export { SERVICE_NAME };

export const COPY = {
  landing: {
    headline: "같은 걸 좋아하는 사람이랑 만나요",
    sub: "외모 스와이프 대신 덕질 궁합. 취미 카드로 소개하고, 궁합 퀴즈로 맞춰 보고, 같이 할 걸 골라요.",
    cta: "시작하기",
    login: "이미 회원이에요",
    features: [
      { title: "덕질 카드가 먼저", body: "사진보다 취미·몰입도·최애가 먼저 보여요." },
      { title: "매칭되면 바로 할 것", body: "같이 할 수 있는 제안 카드 3장으로 첫 마디를 시작해요." },
      { title: "성인만, 본인인증 후", body: "추천은 본인인증을 마친 사람끼리만. 이름은 저장하지 않아요." },
    ],
    company: "회사 소개",
  },
  age: {
    headline: "먼저 나이를 확인할게요",
    sub: `${SERVICE_NAME}는 성인만 이용해요. 안전한 만남을 위해 먼저 확인할게요.`,
    hint: "생년월일은 프로필에 표시되지 않고 연령대(20대 초반)로만 보여요.",
    error: "날짜를 다시 확인해 주세요",
    cta: "계속하기",
    loginLink: "이미 회원이에요",
    minor: {
      headline: `${SERVICE_NAME}는 성인만 이용해요`,
      sub: "만 19세가 되면 다시 만나요.",
      back: "처음으로",
    },
  },
  phone: {
    headline: "휴대폰 번호를 알려 주세요",
    loginHeadline: "휴대폰 번호로 로그인해요",
    sub: "번호는 본인 확인용이며 프로필에 절대 표시되지 않아요.",
    placeholder: "010-0000-0000",
    request: "인증번호 받기",
    resend: "재전송",
    resendIn: (sec: number) => `재전송 (${sec}초 후)`,
    codeLabel: "인증번호 6자리",
    codeHint: "문자로 온 숫자를 입력해 주세요",
    submit: "인증하고 시작하기",
    loginSubmit: "로그인",
    wrongCode: "코드가 맞지 않아요",
    rateLimited: "요청이 많아요. 1시간 후 다시 시도해 주세요",
    consentsRequired: "필수 약관에 동의해 주세요",
    newHere: "처음이에요",
    changePhone: "번호 바꾸기",
  },
  consents: {
    all: "전체 동의",
    terms: "이용약관",
    privacy: "개인정보처리방침",
    youth: "청소년보호정책",
    marketing: "새 추천·이벤트 알림 받기 (선택)",
    required: "[필수]",
    optional: "[선택]",
    view: "보기",
    /** 15_auth §0-6 설명의무: 약관 요약 3줄 — evidence_snapshot 동의는 이 요약을 본 뒤 terms 와 함께 true */
    evidenceSummary: [
      "신고가 접수되면 최근 대화 50개와 프로필이 운영팀에 자동으로 전달돼요.",
      "연락처·링크는 매칭 3일 후부터 보낼 수 있어요. 그 전엔 [연락처 숨김]으로 보여요.",
      "만 19세 미만은 이용할 수 없고, 본인인증 결과가 다르면 계정이 정지돼요.",
    ],
  },
  basic: {
    headline: "뭐라고 부르면 돼요?",
    sub: `닉네임은 ${NICKNAME_MIN}~${NICKNAME_MAX}자. 실명이 아니어도 괜찮아요. 지역은 구까지만 물어요.`,
    nickname: "닉네임",
    nicknameHint: `${NICKNAME_MIN}~${NICKNAME_MAX}자`,
    gender: "성별",
    genders: { female: "여성", male: "남성", unspecified: "선택 안 함" },
    region: "지역",
    sido: "시/도",
    sigungu: "시/군/구",
    regionHint: "동 단위는 묻지 않아요",
    availabilityHeadline: "주로 언제 시간이 나요?",
    availabilitySub: "같은 시간대에 움직이는 사람을 먼저 보여드려요. (최소 1칸)",
    quick: { weekdayEvening: "평일 저녁", weekendDay: "주말 낮" },
    weekdays: ["월", "화", "수", "목", "금", "토", "일"],
    slots: { morning: "아침", afternoon: "오후", evening: "저녁", night: "밤" },
    next: "다음",
  },
  hobbies: {
    headline: "요즘 뭐에 빠져 있어요?",
    sub: "3개만 골라도 시작할 수 있어요. 아직 시작 안 했어도 괜찮아요 — \"관심 있음\"도 취미예요.",
    search: "취미 검색",
    more: "더보기",
    less: "접기",
    selected: (n: number, max: number) => `선택됨 (${n}/${max})`,
    rankHint: "순서 = Top3 · 위로 버튼으로 바꿔요",
    max: "5개까지 고를 수 있어요",
    minHint: "3개만 골라도 시작할 수 있어요",
    sheetTitle: "얼마나 빠져 있어요?",
    favNote: "최애/작품 (선택, 30자)",
    beginner: "아직 시작 안 했어도 괜찮아요",
    request: "찾는 취미가 없어요 → 직접 추가 요청",
    requestNote: "요청은 문의로 접수돼요. 온보딩은 그대로 진행돼요.",
    up: "위로",
    remove: "빼기",
    next: "다음",
    done: "완료",
  },
  quiz: {
    headline: "궁합 퀴즈",
    sub: "3문항만 답해도 추천이 시작돼요. 나머지는 나중에 답하면 정확도가 올라가요.",
    later: "나중에 할게요",
    prev: "이전 문항",
    progress: (n: number, total: number) => `${n}/${total}`,
  },
  card: {
    headline: "이 카드가 사진보다 먼저 보여요",
    sub: "나답게 써 주세요. 최애랑 요즘 빠진 것만 있으면 돼요.",
    preview: "미리보기 (실시간)",
    favNote: "최애",
    favNoteHint: "비우면 카드에서 숨겨요",
    nowInto: "요즘 빠진 것",
    nowIntoHint: "40자",
    examples: "예시",
    exampleChips: ["컴백 무대 정주행", "새 암장 도장깨기", "동네 카페 지도 만들기", "밤샘 보드게임 모임", "필름 스캔 밀린 거 정리"],
    next: "완성",
  },
  photos: {
    headline: "사진은 나중에 올려도 돼요",
    sub: "지금은 덕질 카드만으로 추천을 받아요. 올리면 24시간 안에 확인해요.",
    add: "사진 올리기",
    max: (n: number) => `최대 ${n}장`,
    pending: "검수 대기 · 24시간 안에 확인해요",
    primary: "대표",
    remove: "삭제",
    guide: "대표 사진은 얼굴이 보이는 본인 사진만 승인돼요. 취미·캐릭터 사진은 보조 사진으로 올릴 수 있어요.",
    fileError: "이 파일은 올릴 수 없어요 (JPG/PNG/WebP, 5MB 이하)",
    done: "완료",
    later: "사진은 나중에",
  },
  verify: {
    headline: "본인인증 후 추천이 시작돼요",
    sub: "이름은 저장하지 않아요. 생년월일과 중복 가입 확인에만 써요.",
    steps: { phone: "휴대폰 확인", identity: "본인인증 (이 단계)", photo: "사진 인증 (데이팅 모드용)" },
    start: "인증하기",
    later: "프로필 먼저 다듬기",
    processing: "확인하는 중이에요",
    notAllowlisted: { headline: "지금은 초대된 번호만 인증할 수 있어요", sub: "초대 순서대로 열고 있어요. 열리면 알려드릴게요.", cta: "확인" },
    notConfigured: "지금은 인증할 수 없어요. 잠시 후 다시 시도해 주세요",
    failed: "인증에 실패했어요. 다시 시도해 주세요",
    duplicate: { headline: "이미 가입된 정보예요", sub: "기존 계정으로 로그인해 주세요. 도움이 필요하면 문의로 알려 주세요.", cta: "로그아웃" },
    blocked: { headline: "이 정보로는 가입할 수 없어요", sub: "자세한 사유는 안내할 수 없어요. 문의로 알려 주시면 확인해 드려요.", cta: "확인" },
    mock: {
      title: "본인인증 (개발용 시뮬레이션)",
      body: "실제 인증 대신 결과를 골라 재현해요. 프로덕션에서는 이 선택이 무시돼요.",
      simulate: { success: "성공", fail: "실패 (IDENTITY_FAILED)", minor: "미성년 (MINOR → 정지)", duplicate: "중복 (DUPLICATE_CI)" },
      confirm: "이 결과로 진행",
    },
    prodMockNote: "지금은 초대된 번호만 인증할 수 있어요. 초대 순서대로 열고 있어요.",
  },
  blockedAge: {
    headline: "만 19세 이상만 이용할 수 있어요",
    sub: "입력한 정보는 30일 후 삭제돼요.",
    back: "처음으로",
  },
  suspended: {
    logout: "로그아웃",
    appeal: "이의신청",
    appealed: "이의신청 접수됨 · 72시간 안에 답변드려요",
    endsAt: "해제 예정",
    reason: "사유",
    minorNote: "본인인증 결과에 따른 조치는 이의신청할 수 없어요",
    bannedHeadline: "더 이상 이용할 수 없어요",
    bannedSub: "데이터 처리 안내는 개인정보처리방침을 확인해 주세요.",
    warningHeadline: "경고를 받았어요",
    ack: "확인했어요",
    generic: "계정 이용이 제한됐어요",
    privacy: "개인정보처리방침",
  },
  common: {
    back: "뒤로",
    retry: "다시 시도",
    network: "연결이 잠깐 끊겼어요. 입력한 내용은 저장해 뒀어요. 다시 시도해 주세요.",
    rateLimited: (sec: number) => (sec >= 3600 ? "요청이 많아요. 1시간 후 다시 시도해 주세요" : `요청이 많아요. ${Math.ceil(sec / 60)}분 후 다시 시도해 주세요`),
    optional: "선택",
  },
} as const;
